version: '3.2'
services:
  sut:
    build:
      context: ..
      dockerfile: "github_actions_test/Dockerfile"
    depends_on:
      - db
    env_file:
      - test-config.EXAMPLE
    volumes:
      - ./target:/app/github_actions_test/target
    command: mvn verify
