version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    working_directory: ~/project
    environment:
      UDS_PORT: 5432
    steps:
      - checkout:
          path: ~/project/github_actions_test
      - run:
          name: clone informdb
          command: git clone "git@github.com:inform-health-informatics/Inform-DB.git"
      - run:
          name: docker-compose build
          working_directory: ~/github_actions_test
          command: |
            docker login -u ${DOCKERHUB_USERNAME} -p ${DOCKERHUB_PASSWORD}
            docker-compose -f docker-compose.fake-services.yml -f docker-compose.test.yml build
      - run:
          name: run docker-compose tests
          working_directory: ~/project/testing
          command: docker-compose -f docker-compose.fake-services.yml  -f docker-compose.test.yml up --exit-code-from sut
      - store_test_results:
          path: ~/project/github_actions_test/target/surefire-reports

workflows:
  ci:
    jobs:
      - build:
          context:
            - dockerhub