name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout Repo
        uses: actions/checkout@v2
        with:
          path: github_actions_test
      # try and checkout the same branch as the PR, otherwise revert to develop
      - name: Set output variables
        # gets current branch name
        id: vars
        run: echo ::set-output name=branch::${GITHUB_REF#refs/*/} # ${{ steps.vars.outputs.branch }}
      - name: checkout informdb
        id: checkout-branch
        run: |
          git clone --branch ${{ steps.vars.outputs.branch }} https://github.com/inform-health-informatics/Inform-DB.git \
          || git clone --branch develop https://github.com/inform-health-informatics/Inform-DB.git
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Pull images
        working-directory: github_actions_test
        # Pull the latest image to build, and avoid caching pull-only images.
        run: docker-compose -f docker-compose.fake-services.yml -f docker-compose.test.yml pull
      - name: Cache docker layers
        uses: satackey/action-docker-layer-caching@v0.0.11
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true
      - name: Build docker images
        working-directory: github_actions_test
        run: |
          docker-compose -f docker-compose.fake-services.yml -f docker-compose.test.yml build
      - name: run tests
        working-directory: github_actions_test
        run: |
          docker-compose -f docker-compose.fake-services.yml  -f docker-compose.test.yml up --exit-code-from sut
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v2
        if: always() # always run even if the previous step fails
        with:
          report_paths: '**/target/surefire-reports/TEST-*.xml'
