name: Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    env:
      # enable docker buildkit for faster building
      DOCKER_BUILDKIT: 1
      COMPOSE_DOCKER_CLI_BUILD: 1
    runs-on: ubuntu-latest
    steps:
      - name: checkout Repo
        uses: actions/checkout@v2
        with:
          path: github_actions_test
      - name: checkout informdb
        id: checkout-branch
        run: |
          echo "cloning ${GITHUB_HEAD_REF}" \
          && git clone --branch ${GITHUB_HEAD_REF} https://github.com/inform-health-informatics/Inform-DB.git \
          || git clone --branch develop https://github.com/inform-health-informatics/Inform-DB.git
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push base image
        id: build_base
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile.base
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.event.repository.name }}:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.event.repository.name }}:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.event.repository.name }}:buildcache,mode=max
      - name: Pull images
        working-directory: github_actions_test
        # Pull the latest image to build, and avoid caching pull-only images.
        run: docker-compose -f docker-compose.fake-services.yml -f docker-compose.test.yml pull
      - name: Cache docker layers
        uses: satackey/action-docker-layer-caching@v0.0.11
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true
      - name: Build docker images
        working-directory: github_actions_test
        run: |
          docker-compose -f docker-compose.fake-services.yml -f docker-compose.test.yml build
      - name: run tests
        working-directory: github_actions_test
        run: |
          docker-compose -f docker-compose.fake-services.yml  -f docker-compose.test.yml up --exit-code-from sut
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v2
        if: always() # always run even if the previous step fails
        with:
          report_paths: '**/target/surefire-reports/TEST-*.xml'
