name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
    steps:
    - name: checkout Repo
      uses: actions/checkout@v2
      with:
        path: github_actions_test
    - name: checkout informdb
      uses: actions/checkout@v2
      with:
        repository: "inform-health-informatics/Inform-DB"
        path: Inform-DB
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        # use the same key for same operating system, could try and do for most recent tag of repo?
        key: ${{ runner.os }}
    - name: Build docker
      working-directory: github_actions_test
      run: |
        docker-compose -f docker-compose.fake-services.yml -f docker-compose.test.yml build
    - name: run tests
      working-directory: github_actions_test
      run: |
        docker-compose -f docker-compose.fake-services.yml  -f docker-compose.test.yml up --exit-code-from sut
